# Generated by Django 5.0.6 on 2025-06-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location_anonymization',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferred_transport',
            field=models.CharField(choices=[('DRIVING', 'Private Car'), ('KOMBI', 'Kombi'), ('WALKING', 'Walking'), ('BICYCLE', 'Bicycle'), ('MIXED', 'Mixed Transport')], default='DRIVING', max_length=10),
        ),
    ]
